In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib


%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (10, 8) # set default figure size, 8in by 6in

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC


# Assignment 05: Ensemble Learning and Random Forests

**Due Date:** Friday 11/27/2023 (by midnight)

Please fill in the following in case I accidentally mix up assignment notebooks:

**Name:** Anas Mohammad

**cwid-5:** 22515

## Introduction
In this assignment you will use the MNIST data set to create some ensemble classifiers.  This assignment
is a bit more open ended than some of the previous ones.  So try and create classifiers for submission
that do the tasks as described and are performing relatively well to classify the MNIST digits dataset.

## Part 1: Load and Setup MNIST data

Load the MNIST data set that we have used before, and split it into a training set,
a validation set, and a test set.  Use 50,000 instances for training, 10,000 for validation
and 10,000 for testing.  Be careful that the data is shuffled, e.g. that you have all 10 
digits in about equal proportions in the training, validation and test data sets.

In [3]:
from sklearn.datasets import fetch_openml


In [4]:
#fetching/load MNIST data

X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
(X_train,X_test,y_train,y_test) = train_test_split(X,y,train_size=0.85715)

/Users/mdanas/anaconda3/lib/python3.11/site-packages/sklearn/datasets/_openml.py:1002: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [5]:
X_train.shape

(60000, 784)

In [6]:
X_test.shape

(10000, 784)

In [7]:
#For Validation data
X_val, X_train, y_val, y_train = train_test_split(X_train, y_train, train_size=0.166667) 

In [8]:
X_train.shape

(50000, 784)

In [9]:
X_val.shape

(10000, 784)

## Part 2: Train Classifiers on MNIST training data

Train the following 3 types of classifiers on this MNIST training dataset:

1. Random Forest classifier
2. Extra-Trees classifier
3. SVM classifier.

Try and tune these so they each work individuall well.  Show performance of each of the 3 on the validation set, e.g. report a confusion matrix and raw accuracy for each of the 3 classifiers on validation data.

In [10]:
#Training Classifiers on MNIST Training data
#RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [11]:
#printing performance- Accuracy,Classification report, Confusion matrix

pred = rfc.predict(X_test)
print("The RAW Accuracy is:")
print(accuracy_score(y_true=y_test, y_pred=pred))
print("Classification Report of RFC")
print(classification_report(y_test, pred))
print("Confusion Matrix")
print(confusion_matrix(y_test, pred))

The RAW Accuracy is:
0.9669
Classification Report of RFC
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       992
           1       0.98      0.98      0.98      1173
           2       0.96      0.96      0.96       991
           3       0.97      0.95      0.96      1028
           4       0.96      0.97      0.97       955
           5       0.96      0.96      0.96       924
           6       0.97      0.98      0.98       980
           7       0.97      0.97      0.97      1029
           8       0.96      0.95      0.96       978
           9       0.95      0.94      0.94       950

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

Confusion Matrix
[[ 980    0    1    0    1    0    3    0    7    0]
 [   0 1154    4    7    1    1    1    2    2    1]
 [   6    2  955    4    2    0    5    7    9    1]
 [   0  

In [12]:
#Extra Tree Classifier
clf = ExtraTreesClassifier(n_estimators=100, random_state=0) 

In [13]:
clf.fit(X_train, y_train)

ExtraTreesClassifier(random_state=0)

In [14]:
#printing performance- Accuracy,Classification report, Confusion matrix

pred=clf.predict(X_test)
print("The Raw accuracy:")
print(accuracy_score(y_true=y_test, y_pred=pred))
print ("Classification Report of Extra Trees Classifier")
print(classification_report(y_test, pred))
print ("Confusion Report")
print(confusion_matrix(y_test, pred))

The Raw accuracy:
0.9702
Classification Report of Extra Trees Classifier
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       992
           1       0.99      0.99      0.99      1173
           2       0.97      0.97      0.97       991
           3       0.97      0.95      0.96      1028
           4       0.96      0.97      0.97       955
           5       0.97      0.96      0.97       924
           6       0.97      0.99      0.98       980
           7       0.97      0.97      0.97      1029
           8       0.96      0.96      0.96       978
           9       0.95      0.95      0.95       950

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

Confusion Report
[[ 982    0    1    0    1    0    3    0    5    0]
 [   0 1160    4    5    1    1    0    1    1    0]
 [   6    1  959    2    2    0    3    7   1

In [15]:
#SVC Classifier

svm = SVC(probability=False)
svm.fit(X_train, y_train)

SVC()

In [16]:
#printing perfomance measures for SVC

print('accuracy across train', accuracy_score(y_train, svm.predict(X_train)))
print('accuracy across validation', accuracy_score(y_val, svm.predict(X_val)))
print('accuracy across test', accuracy_score(y_test, svm.predict(X_test)))

accuracy across train 0.9897
accuracy across validation 0.978
accuracy across test 0.9777


## Part 3: Create an Ensemble

Next combine your 3 classifiers into an ensemble (using scikit-learn enesmble methods
as shown in our textbook).  See if you can create an ensemble that outperforms each
individual classifier on the validation set, using soft or hard voting.  

Once you have found an ensemble that performs better than the individual classifiers (or at least
no worse), evaluate it on the test set.  Give raw accuracy and a confusion matrix of the results on
validation and test data.  How much better does it perform compared to individual classifiers?

In [17]:
#Creating an ensemble, performing hard voting

voting_clf = VotingClassifier(
    estimators=[('rfc', rfc), ('tree', clf), ('svm', svm)],
    voting='hard'
)

voting_clf.fit(X_train, y_train)

VotingClassifier(estimators=[('rfc', RandomForestClassifier()),
                             ('tree', ExtraTreesClassifier(random_state=0)),
                             ('svm', SVC())])

In [18]:
for clfs in (rfc, clf, svm, voting_clf):
    clfs.fit(X_train, y_train)
    y_pred = clfs.predict(X_test)
    print(clfs.__class__.__name__, accuracy_score(y_test, y_pred))
    print(confusion_matrix(y_test,y_pred))

RandomForestClassifier 0.967
[[ 981    0    1    0    1    0    3    0    6    0]
 [   0 1153    4    7    1    1    1    1    5    0]
 [   4    1  954    3    3    1    5    6   13    1]
 [   0    3   16  977    0   15    1    5    8    3]
 [   2    2    0    0  925    0    5    1    1   19]
 [   4    1    1    6    3  892    6    1    7    3]
 [   8    3    1    0    0    5  960    0    3    0]
 [   0    4    7    1    9    0    0  993    1   14]
 [   0    5    8    3    3    8    2    0  937   12]
 [   6    3    1   15   12    1    0   10    4  898]]
ExtraTreesClassifier 0.9702
[[ 982    0    1    0    1    0    3    0    5    0]
 [   0 1160    4    5    1    1    0    1    1    0]
 [   6    1  959    2    2    0    3    7   11    0]
 [   2    1   12  980    0   12    2    6   10    3]
 [   1    2    1    0  927    0    7    3    0   14]
 [   2    0    0   11    4  889    8    1    5    4]
 [   6    2    0    0    0    2  968    0    2    0]
 [   0    2    8    0   10    0    0  998

In [19]:
for clfs in (rfc, clf, svm,voting_clf):
    clfs.fit(X_train, y_train)
    y_pred = clfs.predict(X_val)
    print(clfs.__class__.__name__, accuracy_score(y_val, y_pred))
    print(confusion_matrix(y_val, y_pred))

RandomForestClassifier 0.9689
[[ 934    0    1    0    1    0    4    0    5    1]
 [   0 1101    6    2    2    1    0    1    4    0]
 [   3    2  987    2    6    2    2    5    2    0]
 [   1    2    4  993    0   11    2    9    9    2]
 [   4    0    2    0  969    0    7    1    3   11]
 [   2    1    0    5    3  868    8    2    6    2]
 [   4    3    1    0    3    6  938    0    3    0]
 [   0    8   10    0    3    0    0 1000    0   10]
 [   1    5    1   15    3    6    6    3  925   11]
 [   3    5    0   19   16    4    1    8    4  974]]
ExtraTreesClassifier 0.9715
[[ 933    0    0    0    1    0    4    0    7    1]
 [   0 1104    5    2    2    1    0    1    2    0]
 [   3    2  983    3    5    2    2    6    4    1]
 [   2    1    7  994    1   10    1    7    8    2]
 [   4    1    1    0  968    0    7    1    2   13]
 [   3    0    1    7    1  870    9    0    6    0]
 [   6    3    0    0    2    7  939    0    1    0]
 [   0    7    6    0    3    0    0 101

## Part 4: Create a Blender Stacking Ensemble

Run the individual classifiers from the previous exercise to make predictions
on the validation set, and create a new training set with the resulting
predictions: each training instance is a vector containing the set of predictions
from all your classifiers for an image, and the target is the image’s class. Train
a classifier on this new training set. Congratulations, you have just trained a
blender, and together with the classifiers it forms a stacking ensemble! Now
evaluate the ensemble on the test set. For each image in the test set, make
predictions with all your classifiers, then feed the predictions to the blender to
get the ensemble’s predictions. How does it compare to the voting classifier
you trained earlier?

In [20]:
#Now creating a blender, running the individual classifiers on validation set. 
y_pred_val_rf = rfc.predict(X_val)
y_pred_val_clf = clf.predict(X_val)
y_pred_val_svm = svm.predict(X_val)

In [21]:
print(y_pred_val_rf.shape)
print(y_pred_val_clf.shape)
print(y_pred_val_svm.shape)
print(y_val.shape)

(10000,)
(10000,)
(10000,)
(10000,)


In [22]:
columns = ['RF','ET','SVM']
data = np.column_stack((y_pred_val_rf.T,y_pred_val_clf.T,y_pred_val_svm.T))
df = pd.DataFrame(data,columns=columns)
print(df.shape)

(10000, 3)


In [23]:

blender = RandomForestClassifier(n_estimators=1000)

In [24]:
#fitting the blender with validation data
blender.fit(df,y_val)

RandomForestClassifier(n_estimators=1000)

In [25]:
y_pred_test_rf = rfc.predict(X_test)
y_pred_test_clf = clf.predict(X_test)
y_pred_test_svm = svm.predict(X_test)

In [26]:
columns = ['RF','ET','SVM']
test_data = np.column_stack((y_pred_test_rf.T,y_pred_test_clf.T,y_pred_test_svm.T))
test_df = pd.DataFrame(test_data,columns=columns)
print(df.shape)

(10000, 3)


In [27]:
y_pred = blender.predict(test_df)
y_pred.shape

(10000,)

In [28]:
y_test.shape

(10000,)

In [29]:
print("Blender Report",classification_report(y_test,y_pred))

Blender Report               precision    recall  f1-score   support

           0       0.98      0.99      0.98       992
           1       0.99      0.99      0.99      1173
           2       0.97      0.97      0.97       991
           3       0.97      0.96      0.97      1028
           4       0.96      0.98      0.97       955
           5       0.98      0.96      0.97       924
           6       0.98      0.99      0.98       980
           7       0.97      0.97      0.97      1029
           8       0.96      0.97      0.97       978
           9       0.98      0.95      0.96       950

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

