# Test 01: Midterm Exam (CSci 574 Fall 2023)

Please fill in the following for your submitted exam work:

**Name**: Anas Mohammad

**cwid-5**: 22515


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

from sklearn.datasets import make_regression
from sklearn.datasets import make_friedman1 
from sklearn.datasets import make_classification
from sklearn.datasets import make_blobs

# Question 1: Numpy, Functions and Array Indexing

Write the function described.  You are given the function signature and
function documentation to use, and some examples of the results your
function should produce.

In [2]:

def array_forty_two(a):
    
    """Given a numpy array, a copy of the array is made.  Then the largest
    value in the original array is determined and replaced with 42.  Also the
    smallest value in the array is determined and replaced with -42.  The copy
    with the modified max=42, min=-42 is returned as a result

    Parameters
    ----------
    a - A numpy array of any shape

    Returns
    -------
    copy_a - A copy of the original a, but where the maximum value has been
        replaced by 42 and the minimum by -42
    """
    y = np.copy(x)
    max_value = np.max(y)
    y[y == max_value] = 42
    min_value = np.min(y)
    y[y == min_value] = -42
    return y




In [3]:
x = np.array([1, 9, 5, 3, 2, 4, 8, 6, 10]).astype(float)
y = array_forty_two(x)

In [4]:
np.random.seed(42)
x = np.random.rand(5, 4)
y = array_forty_two(x)
print(x)

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]]


In [5]:
print(y)

[[  0.37454012   0.95071431   0.73199394   0.59865848]
 [  0.15601864   0.15599452   0.05808361   0.86617615]
 [  0.60111501   0.70807258 -42.          42.        ]
 [  0.83244264   0.21233911   0.18182497   0.18340451]
 [  0.30424224   0.52475643   0.43194502   0.29122914]]


# Question 2: Linear Regression

In the following question you will be asked to generate a made up dataset
that will be used for fitting a linear regression.  Generate the dataset shown,
then fit the asked for model and report the results asked for.

In [6]:
from sklearn.datasets import make_friedman1 
X, y = make_friedman1(n_samples=500, n_features=10, noise=0.1, random_state=4)
x = X[:,3].reshape(-1,1)
y.reshape(-1)

model = LinearRegression().fit(x,y)
intercept = model.intercept_
slope = model.coef_[0]
print("Intercept:", intercept)
print("Slope:", slope)

Intercept: 9.553486535495628
Slope: 9.779040643896208


In [7]:
y_predict = model.predict(x)
rmse = mean_squared_error(y, y_predict)
rmse = rmse**0.5
print("RMSE=", rmse)
r2_ = model.score(x, y)
print("R^2 fit",r2_)


RMSE= 4.090264984541661
R^2 fit 0.3424546829804064


In [8]:
x = x.reshape(500)

In [9]:
x.shape

(500,)

In [ ]:
plt.scatter (x,y);
plt.xlabel("X")
plt.ylabel("Y")
(m,b) = np.polyfit(x, y_predict, 1)
plt.plot(x, m*x+b, color="grey")
plt.legend(["X vs Y ", "fitted model"]);


# Question 3: Logistic Regression

In the following question you will be asked to generate a random dataset with a binary category for the training label.  Generate the asked for dataset and perform the tasks to build and report on the performance of a classification model of the data.

In [ ]:
from sklearn.datasets import make_blobs
X, y = make_blobs(n_samples=100, centers=2,
                  n_features=2,
                  cluster_std=11, random_state=11)

In [ ]:
x = X[:,0]
x

In [ ]:
y1 = X[:,1]

In [ ]:
plt.figure(figsize=(15,15))
plt.scatter(x=x[np.where(y==1)], y=y1[np.where(y==1)],color='red')
plt.scatter(x=x[np.where(y==0)], y=y1[np.where(y==0)],color='blue')

In [ ]:
model = LogisticRegression().fit(X,y)

In [ ]:
print(model.coef_, model.intercept_)

In [ ]:
score = model.score(X,y)
print(score)

In [ ]:
predict_rain = model.predict(X)
con_matrix = confusion_matrix(y,predict_rain)
print(con_matrix)